services:
  - type: web
    name: sports-image-batch-tool
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: GETTY_API_KEY
        sync: false
